from enum import Enum

class AllureTag(str, Enum):
    USERS = "USERS"
    REGRESSION = "REGRESSION"
    FILES = "FILES"
    COURSES = "COURSES"
    EXERCISES = "EXERCISES"
    AUTHENTICATION = "AUTHENTICATION"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITIES = "CREATE_ENTITIES"
    UPDATE_ENTITIES = "UPDATE_ENTITIES"
    DELETE_ENTITIES = "DELETE_ENTITIES"
    VALIDATE_ENTITY  = "VALIDATE_ENTITY"



